### ISSUE TITLE
Unfortunately I cannot access the Grafana webservice.

### ISSUE THREAD

**Issue by fefi-byte** [remijouannet/graftorio2#15]
Attached is the console log and the .yml file.

[docker-compose.zip](https://github.com/remijouannet/graftorio2/files/8208904/docker-compose.zip)
[log.txt](https://github.com/remijouannet/graftorio2/files/8208916/log.txt)

**Comment by remijouannet** [comment]
Hello,
looks like you have permissions issue, the compose file work on my macbook, maybe the compose need some tweak to work on linux
