### ISSUE TITLE
graftorio2 unrecoverable error

### ISSUE THREAD

**Issue by LegendaryGeek** [remijouannet/graftorio2#16]
![image](https://user-images.githubusercontent.com/45850917/158935220-a5cfecd6-16bb-4fb5-9986-6fcab5f64ab6.png)
so i got this when trying to load my factorio world. only change was removing a few veheicle mods that shouldnt have been an issue.

**Comment by remijouannet** [comment]
Hello, is that possible to send me your save ? it will be easier to debug for me

**Comment by LegendaryGeek** [comment]
i can. and here you are
[StreamSave2.zip](https://github.com/remijouannet/graftorio2/files/8309487/StreamSave2.zip)

**Comment by remijouannet** [comment]
Hello, at last fix in 0.0.17
