### ISSUE TITLE
Power poles do not restore copper connections after being destroyed

### ISSUE THREAD

**Issue by anpavlov** [remijouannet/graftorio2#20]
When power pole get destroyed by biter or weapon and ghost entity is created, the ghost entity does not show previously existing connections of copper cable and thus not restoring them when pole is built again

https://user-images.githubusercontent.com/10996983/197990503-37141f43-d1fb-4c65-af4b-168f972063fc.mp4

**Comment by anpavlov** [comment]
By deactivating mods one by one, found it is a graftorio2 issue

**Comment by marimelon** [comment]
https://github.com/remijouannet/graftorio2/blob/fb0b352fd8a215db335fa1a1e99454f5ee6c40fc/power.lua#L113-L116

**Comment by remijouannet** [comment]
should be fix in 0.0.18
