### ISSUE TITLE
Cannot checkout repository on windows

### ISSUE THREAD

**Issue by Zincfox** [remijouannet/graftorio2#35]
While attempting to clone for my two pull requests, I discovered that the colon characters (`:`) in several of the dashboard definitions file names are not allowed on windows. The result of this is that the clone succeeds, but the checkout fails - with `git restore --staged .` one can "un-delete" the other files, but the only way I found to not include the fake deletion of these dashboard definitions in a commit was to work inside WSL (there at least `git restore --staged config` worked to exclude the deletions from the commit, which I could then finish back under windows).

The clone-error for reference:
```
error: invalid path 'config/grafana/dashboards/Factorio/1.1 - Default: Electricity.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
After that both `git restore --source=HEAD :/` and `git restore --staged .` printed
```error: invalid path 'config/grafana/dashboards/Factorio/1.1 - Default: Electricity.json'```
for each file with a colon in its name.

I just wanted to make you aware of this, either to rename the files or as documentation of the workaround for other contributors.

**Comment by remijouannet** [comment]
do you have time to rename everything in a PR ?

**Comment by Zincfox** [comment]
yes, see the [linked PR](https://github.com/remijouannet/graftorio2/pull/38).
