### ISSUE TITLE
train stats aren't working

### ISSUE THREAD

**Issue by phdoerfler** [remijouannet/graftorio2#5]
https://github.com/remijouannet/graftorio2/blob/master/control.lua#L31-L41 suggests there are a number of train related metrics, yet I can't find any in prometheus:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/163428/114734209-4e2f6d00-9d44-11eb-8dfd-0db1c5444728.png">
Mod version is 0.0.13, Factorio is current stable 1.1.30.

**Comment by remijouannet** [comment]
i'm gonna release a new version soon since someone made a PR, i'm gonna check the train stats

**Comment by remijouannet** [comment]
i see you have metrics name with typo "coount" "entitybuild", did you edit the mod code ? i did not find any typo in the source

**Comment by phdoerfler** [comment]
No, we did not alter the mod. It was downloaded through Factorio‘s mod syncing facility.

**Comment by Lupo42** [comment]
Regarding "typos": Those may be the result of a race condition hitting when the mod is writing to the game.prom file at the same time the prometheus node-exporter is reading from it.

Running
`$ while true; do cat script-output/graftorio2/game.prom | grep -v -e factorio_entity_build_count_ -e factorio_kill_count_ -e factorio_fluid_production_ -e factorio_item_production_ -e factorio_items_launched_ -e '^\s*$' -e '^#' -e factorio_tick ; done`
for some time yields hits like
`factoriio_kill_count_input{force="player",name="big-worm-turret"} 5`
eventually.

**Comment by remijouannet** [comment]
the train stats are fix in the 0.0.14 version, 
regarding the race condition i can't really fix it, factorio doesn't give many api call to manipulate file
