### ISSUE TITLE
sometimes `factorio_logistic_network_items` does not include science packs

### ISSUE THREAD

**Issue by naikrovek** [remijouannet/graftorio2#8]
I'm not sure why, but sometimes the `factorio_logistic_network_items` has plenty of stuff in it, but science packs stop being written out to `game.prom`.

I don't know how to reproduce, I don't know how to trigger it, but I have millions of science packs in logistics chests, and none of them show up in `game.prom`.  They were working, then they weren't.   ¯\\\_(ツ)\_/¯

**Comment by naikrovek** [comment]
ah, I think running factorio headless includes the science pack data, and running normally doesn't.

**Comment by remijouannet** [comment]
Hello,
I Will try to look at it this week-end

**Comment by naikrovek** [comment]
I should add that I'm using Windows for both the GUI client and the headless server.

**Comment by naikrovek** [comment]
This may be a bug in Factorio, actually.  Switching back to full game client from standalone server shows the same save file now correctly reporting the science packs in the logistic network items dataset (or whatever the term is).

I expect that these will stop being emitted by your mod at some point, and I will again see "no data" on those gauges.  I don't know what the trigger was yesterday, so I don't know when I'll hit it today, but if I can associate it with something I'm doing, I'll let you know.
